apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: envd-server-pod-webhook
  name: envd-server-pod-webhook
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envd-server-pod-webhook
  template:
    metadata:
      labels:
        app: envd-server-pod-webhook
    spec:
      tolerations:
        - key: acme.com/lifespan-remaining
          operator: Exists
          effect: NoSchedule
      containers:
        - image: envd-server-pod-webhook:latest
          imagePullPolicy: Never
          name: envd-server-pod-webhook
          env:
            - name: TLS
              value: "true"
            - name: LOG_LEVEL
              value: "trace"
            - name: LOG_JSON
              value: "false"
          volumeMounts:
            - name: tls
              mountPath: "/etc/admission-webhook/tls"
              readOnly: true
      volumes:
        - name: tls
          secret:
            secretName: envd-server-pod-webhook-tls
