apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "envd-server.tensorchord.ai"
webhooks:
  - name: "envd-server.tensorchord.ai"
    namespaceSelector:
      matchLabels:
        admission-webhook: enabled
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "*"
    clientConfig:
      service:
        namespace: default
        name: envd-server-pod-webhook
        path: /validate-pods
        port: 443
      caBundle: |
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lVVG1pQ3ZrM2lW
        OXFDb05PcGJoSXAzU3p0cDE0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0x6RUxNQWtHQTFVRUJoTUNR
        VlV4SURBZUJnTlZCQU1NRjJWdWRtUXRjMlZ5ZG1WeUxYQnZaQzEzWldKbwpiMjlyTUI0WERUSXlN
        VEl4T1RFd05ETTFPVm9YRFRJek1USXhPVEV3TkRNMU9Wb3dMekVMTUFrR0ExVUVCaE1DClFWVXhJ
        REFlQmdOVkJBTU1GMlZ1ZG1RdGMyVnlkbVZ5TFhCdlpDMTNaV0pvYjI5ck1JSUJJakFOQmdrcWhr
        aUcKOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTJOdDdtTUFFdFo0SEdxQm5BN0puK3l5NTJR
        bkZoK0hQcHcvKwowbllsRUR2Nmh3ejZuYnVMY1htZ2F5Y1ZTWEMzUFg4ZWdxNllUVWZWQlp1M1p2
        UlRKUitGN3J4VWkzeU5FZUdPCkhtMmdaUkE2YlR3ZTBiSWxBSEdiUU1sSEhHd2xrd21iU2hGQ0h5
        RkkzUnI0UlhqRmJTQlpqeVFxdWxOdjhXT0wKeENrOUNWbTBzbHIzRlF1ZlRrY2ZRUEorcEN5NzJB
        NnpQVlVkdzQzVVhDcFZoQ0FjWXJCTFlHczhxcnhhZjc4MwpoVGdTaGxabFNMTnlBbGIrNGh2eVhP
        Q2NhN3EwcVlTNUJZZGRUUllwVE15cjVTQlI2dm5oVUhrV1g1azlUdTJ2CmxubGxHbUU2MndOeWpP
        b2VrenFTcXd3RjhGaUJsSFd4ZytxTWZkN1dEaDYvazhGL1J3SURBUUFCbzFNd1VUQWQKQmdOVkhR
        NEVGZ1FVMFpvSEtxbWNDTFZnaDFUUmRHTWhCeDZWcHdFd0h3WURWUjBqQkJnd0ZvQVUwWm9IS3Ft
        YwpDTFZnaDFUUmRHTWhCeDZWcHdFd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcw
        QkFRc0ZBQU9DCkFRRUF0a042ZmlscVBFSnhzbGJSVER4WC9remlKQ3dZNGJZY3lEMFZ5K1liUUE1
        S0huVURmUDUzOEFUcGFNUE0KRzFyc3BSN1d4YXBQc21WZXJheGRWdW5aaVhUMk9uWHQ0MUo0N2t2
        NWw1NmgrSnViU2c0WHlnUU9FUEgzTmQzcQpHZWEwQ3lJN1JnZFJ2Y01tZFlhUWNuZFZyQjBUNy9Y
        ZGRpbEp2UTJrTnB5dmxYTk14VUp5R1BoZy9tditETmtCCmt2Z1dmMGNxRTY2S002OWcyVzdhUGVj
        VStCbEhsSFhjcFBCRE14M3NFSHBTSEJmQmtlR1RySXJSdnZJMG1VcU4KSjZPbHFxZG1SdXA3YUdi
        Z0hWMUI4Y0hwcStqV0NsMExyN2lxYWd3TEg3MFNraEt5RngvNzA2eFZLTG1sZjU5ZQpxcXBUOC92
        cE43ZVNQZjl6aUVIOHFONzlXQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 2
